apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/ssl/ca.pem
    server: https://{{master_ip_address}}:6443
  name: local
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
kind: Config
preferences: {}
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/ssl/{{ansible_default_ipv4.address}}.pem
    client-key: /etc/kubernetes/ssl/{{ansible_default_ipv4.address}}-key.pem
