---
- name: create repos backup directory
  shell: mkdir -p /etc/yum.repos.d-back
  ignore_errors: yes
- name: backup repos file
  shell: cp /etc/yum.repos.d/* /etc/yum.repos.d-back
  ignore_errors: yes

- copy:
    src: "{{role_path}}/files/docker-ce.repo"
    dest: /etc/yum.repos.d/
    owner: root
    group: root
- copy:
    src: "{{role_path}}/files/selinuxConfig"
    dest: /etc/selinux/config
- name: stop the firewall
  shell: systemctl stop firewalld.service
  ignore_errors: yes
- name: stop the firewall
  shell: systemctl disable firewalld.service
  ignore_errors: yes
- name: set enforce 0
  shell: set enforce 0
  ignore_errors: yes

- name: modprobe br_netfilter
  shell: modprobe br_netfilter

- name: modify sysctl.config
  shell: echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.conf
- name: modify sysctl.config
  shell: echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.conf


#- name: copy br_netfilter to /etc/sysconfig/modules/
#  copy: src={{role_path}}/files/br_netfilter.modules dest=/etc/sysconfig/modules mode=755
